###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    redis:
      image: redis:alpine
      container_name: laraveldocker-redis

    mysql:
      image: mysql:5.7
      container_name: laraveldocker-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=laraveldocker
        - MYSQL_USER=app
        - MYSQL_PASSWORD=password
      ports:
        - "8082:3306"

    webserver:
      image: nginx:alpine
      container_name: laraveldocker-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: laraveldocker-php-fpm
      working_dir: /application

      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.1/fpm/conf.d/99-overrides.ini

